---
title: "ERGM"
author: "Peng-Ting Kuo"
format: pdf
editor: visual
---

# Setup

```{r Packages}
#| warning: false
library(network)
library(ergm)
library(devtools)
library(haven)

# df1 regards EU as one member
df1 <- read.csv("./Data/ergm_dyad_year_eun.csv")

# df2 regards EU members seperately
df2 <- read.csv("./Data/ergm_dyad_year_eu_disagg.csv")
```

```{r Preprocessing}
ergm_df <- ergm_df %>%                                                                      
    mutate(across(starts_with("severity_"), ~replace_na(., 0)),                                          across(starts_with("disputed_sector_"), ~replace_na(., 0)),                                   desta = replace_na(desta, 0),
           bilateral_fta = replace_na(bilateral_fta, 0),
           dispute_count = replace_na(dispute_count, 0))        
```

# ERGM

```{r Network Analysis}
# Example: Create a network object from an adjacency matrix
# Replace 'my_matrix' with your actual adjacency matrix
my_network <- network(my_matrix, directed = FALSE)

# Example: Use a sample network included in the package (e.g., the Florentine marriage network)
data(florentine)
flomarriage # View basic information about the network

```
